; ============================================================================
; WISENS-AI - platformio.ini
; Carte : TTGO LoRa32 v2.1 (ESP32), framework ESP-IDF
; ============================================================================

[env:ttgo-lora32-v21]
platform = espressif32
board = ttgo-lora32-v21
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_port = COM3
monitor_port = COM3

; Niveau de log ESP-IDF (utile pour voir les logs wifi_manager en debug)
build_flags =
    -DCORE_DEBUG_LEVEL=3

    